### PR TITLE
A program in linear search

### LINKED ISSUE #32: Linear Search using C
Try to implement linear search using C.

### PR DESCRIPTION
**Pull request by DaemonOnCode**
Implemented linear search using C
Fixes #32

### CODE REVIEW

**Comment by DaemonOnCode** [comment]
What can I improve?

**Comment by tusharjuneja06** [comment]
Your code is not vaild plzz check and then resend it

**Comment by tusharjuneja06** [comment]
@DaemonOnCode

**Comment by DaemonOnCode** [comment]
If I work on it and resend it will you accept it?
Genuinely asking bro, you know exactly why.

**Pull request closed without merging**
